#!/bin/bash

JSONLD=application/ld+json
TTL=application/x-turtle
TTL2=text/turtle
RDF=application/rdf+xml
N3=text/rdf+n3
NTRIPLES=text/plain

curl --header "Accept: $JSONLD;$TTL;$TTL2;$RDF;$N3;$NTRIPLES" "$@"

